server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://tpznlqchnblwze:35e508c2b30eebf4b8ba7db591af73697485f48b7587554fdd81be1eec08cffb@ec2-54-196-33-23.compute-1.amazonaws.com:5432/d9kdg214posvd9
    username: tpznlqchnblwze
    password: 35e508c2b30eebf4b8ba7db591af73697485f48b7587554fdd81be1eec08cffb
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hivernate:
      ddl-auto: none


application:
  description: Projeto criado para o bootcamp DIO - Santander
  version: 1.0